export enum Events {
  SEND_MESSAGE = "SEND_MESSAGE",
  GET_ALL_MESSAGES = "GET_ALL_MESSAGES",
  UPDATE_ROOM = "UPDATE_ROOM",
  UPDATE_LAST_MESSAGE = "UPDATE_LAST_MESSAGE",
  REACT_TO_MESSAGE = "REACT_TO_MESSAGE",
  READ_ROOM = "READ_ROOM"
}
