import Head from "next/head";
import Modal from "../components/Modal";
import { useRouter } from "next/router";
import Layout from "../layout";
import { trpc } from "../utils/trpc";
import { useState, useRef } from "react";
import { Dialog } from "@headlessui/react";
import { signIn, useSession } from "next-auth/react";

const Home = () => {
  const router = useRouter();
  const { data: session, status } = useSession();

  if (!session && status !== "loading" && typeof window !== "undefined")
    signIn();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout></Layout>
    </>
  );
};

export default Home;
